[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]
# Do not set secrets here. The MCP server reads CONTEXT7_API_KEY from the environment.
# Export CONTEXT7_API_KEY in your shell or load it from a local .env (git-ignored).
