repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/google/yamlfmt
    rev: v0.12.0
    hooks:
      - id: yamlfmt
        name: Format YAML files
        description: "Uses yamlfmt to format YAML files to a standard style."
        entry: yamlfmt
        language: golang
        types:
          - yaml
