name: kri-local-rag
services:
  # ---------- Local Weaviate database ------------------------------------------------
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.1
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:50051:50051"
    volumes:
      - weaviate_db:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: 'none' # We are providing vectors manually
      ENABLE_MODULES: 'text2vec-huggingface,reranker-huggingface' # Still needed for reranker
      CLUSTER_HOSTNAME: 'node1'
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/v1/.well-known/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # ---------- Local LLM server for generating RAG answers ---------------------------------------------------
  ollama:
    image: ${OLLAMA_IMAGE:-ollama/ollama:latest}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama_models:/root/.ollama
    ports:
      - "127.0.0.1:11434:11434"
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  # ---------- RAG App Container (supports both web app and CLI) -----------------------------------------
  app:
    build:
      context: ..  # project root
      dockerfile: docker/app.Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../backend:/app/backend  # Live backend code
      - ../frontend:/app/frontend  # Live frontend code
      - ../tests:/app/tests        # Live tests
      - ../data:/app/data  # Live data access
      - ../logs:/app/logs  # Live log access
      - ../tests:/app/tests      # Mount tests for in-container testing
      - hf_cache:/root/.cache/huggingface
    working_dir: /app
    # Auto-start Streamlit when container starts
    command: ["streamlit", "run", "frontend/rag_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    environment:
      # Point the Python code to the other services inside the compose network
      - OLLAMA_URL=http://ollama:11434
      - WEAVIATE_URL=http://weaviate:8080

  # ---------- One-off Ingestion Utility -----------------------------------------
  ingester:
    profiles: ["ingest"]
    image: kri-local-rag-app   # reuse the APP image
    depends_on:
      - weaviate
      - ollama
    volumes:
      - ../backend:/app/backend  # Live backend code
      - ../data:/app/data  # Live data access
      - ../logs:/app/logs  # Live log access
      - ../tests:/app/tests      # Mount tests for in-container testing
      - hf_cache:/root/.cache/huggingface
    command: ["python", "backend/ingest.py", "/app/data"]

volumes:
  weaviate_db:
  ollama_models:
  hf_cache:
