name: kri-local-rag-ci

services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.0
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: 'none'
      #ENABLE_MODULES: 'text2vec-huggingface,reranker-huggingface'
      CLUSTER_HOSTNAME: 'node1'
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/v1/.well-known/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  app:
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../backend:/app/backend
      - ../frontend:/app/frontend
      - ../tests:/app/tests
      - ../data:/app/data
      - ../logs:/app/logs
    working_dir: /app
    environment:
      - OLLAMA_URL=http://ollama:11434
      - WEAVIATE_URL=http://weaviate:8080
      - OLLAMA_MODEL=cas/mistral-7b-instruct-v0.3
