name: Meta linters (workflows, YAML, Dockerfiles)

on:
  pull_request:
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"
      - "**/*.yml"
      - "**/*.yaml"
      - "Dockerfile"
      - "docker/**"
  push:
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"
      - "**/*.yml"
      - "**/*.yaml"
      - "Dockerfile"
      - "docker/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: meta-linters-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: Actionlint (workflows)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
  yamllint:
    name: Yamllint (repo YAML)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          format: github
          strict: true
  hadolint:
    name: Hadolint (Dockerfiles)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/app.Dockerfile
          format: sarif
          output-file: hadolint.sarif
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint.sarif
